version: '2.1'
services:
  node:
    image: node:latest
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - 3000
    ports:
      - "${EVENTS_PORT:-8082}:3000"
